### ISSUE TITLE
Really low framerate (CT.exe + FPS=75 + NoSync)

### ISSUE THREAD

**Issue by donizettilorenzo** [Leon280698/CT#11]
Got ~30 FPS nearly everywhere (in the start screen too), how is this possible?

**Comment by donizettilorenzo** [comment]
Found the culprit by myself now :D it's the Creative OpenAL (I use an old Audigy 2 ZS). Using DirectSound (defaultdriver=true) there's no issue.

**Comment by donizettilorenzo** [comment]
OpenAL Soft (to use EAX 3 with EAXEFX) gives the same results. Solution: force the FPS limit through RTSS (MSI Afterburner companion application).

**Comment by Leon280698** [comment]
Yes, thats an OpenAL Soft issue. Same problem with the original exe. I fixed it but it’s not available yet unless you build from source

**Comment by donizettilorenzo** [comment]
About OpenAL Soft and EAX, now you can get EAX acceleration directly through OpenAL/EFX bypassing the D3Sound stack (DSOAL/etc) with this: https://github.com/bibendovsky/eaxefx

**Comment by Leon280698** [comment]
Yeah, I know. You don’t even need eaxefx. It’s functionality hass been merged into OpenAL Soft so that can be used directly
