### ISSUE TITLE
Crash when activating OpenGL renderer

### ISSUE THREAD

**Issue by HWG90** [Leon280698/CT#12]
[CT.log](https://github.com/Leon280698/CT/files/6310391/CT.log)

Upon activating the OpenGL renderer, getting an error - using Origin version, tried Steam version now too - same issue. Is there a way to set the renderer before going in game?

**Comment by HWG90** [comment]
Resolved by using provided OpenGLDrv 4.6

**Comment by Leon280698** [comment]
Glad it could be resolved but I'm just leaving this here for future reference:
The crash happened when using the `userendev opengl` console command. This command allows switching the active renderer during gameplay and is mainly intended for testing and not very stable. The proper way to tell the game to use a specific render device is by setting the option in System.ini. CT.exe also supports it as a command line parameter in the form of `CT.exe -rendev=<name>`
