### ISSUE TITLE
FOV breaks crosshair HUD

### ISSUE THREAD

**Issue by RC1207** [Leon280698/CT#13]
Hello, I have encountered a problem with the newest version of the fix (2.6), I can not confirm if this issue is only present in the latest version since I did not test it in the older ones. 
Basically, if your FOV setting is higher than 100 then when you aim down your pistol's sights the crosshair stays on the screen. The same thing happens with the DC-17m (assault rifle mode) when you push it above 115. I tested numerous in-game settings and the only one that had an effect on the crosshair was FOV (I was running the vanilla game only with this fix applied). Mods that add/modify HUD elements also seem to have no effect on this either.
I like to play on 120FOV setting but I also can not stand always on intrusive crosshair when aiming down sights so I thought I would bring it up.

Cheers!

**Comment by Leon280698** [comment]
That's how the game handles the crosshair drawing. It literally checks if the current FOV is lower than the default value and if it is, it skips drawing. With 120 you'll never get below that value, even if zoomed in so the reticle is always drawn. Nothing can be done about that.

**Comment by Leon280698** [comment]
I actually had another look and found a workaround that isn't too bad. So expect that to be included in the next version :)

**Comment by RC1207** [comment]
That is great to hear! Will be looking forward to that!
