### ISSUE TITLE
OpenGL - glGetError

### ISSUE THREAD

**Issue by Levan7** [Leon280698/CT#15]
What i understood according to read me file i changed RenderDevice to OpenGLDrv.OpenGLRenderDevice

Made it look like this
```
[Engine.Engine]
CacheSizeMegs=32
UpdateDynamicLightmaps=False
RenderDevice=OpenGLDrv.OpenGLRenderDevice
;RenderDevice=Engine.NullRenderDevice
;RenderDevice=OpenGLDrv.OpenGLRenderDevice
;RenderDevice=PixoDrv.PixoRenderDevice
AudioDevice=ALAudio.ALAudioSubsystem
;AudioDevice=XboxAudio.XboxAudioSubsystem
```
I got an error message stating 

```
History: UGameEngine::Draw <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- UGameEngine::Tick <- UpdateWorld <- MainLoop
Exit: Exiting.
Log: Waiting for file streaming thread to finish...
Exit: Name subsystem shut down; usage 31082 names (31634 max), 938 KB (1043 KB alloc)
Uninitialized: Log file closed, 03/28/22 20:37:09
```

Using nvidia 1050 ti - is it because of hardware limitation not supporting latest open gl

on default system.ini file if i type ingame userendev opengl getting this error

Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing UWindowsClient::ShutdownAfterError
Log: Waiting for file streaming thread to finish...
Exit: OpenAL Audio subsystem shut down.
Critical: General protection fault!

```
History: UGameEngine::Tick <- UpdateWorld <- MainLoop
Exit: Exiting.
Log: Waiting for file streaming thread to finish...
Exit: Name subsystem shut down; usage 42467 names (43019 max), 1309 KB (1383 KB alloc)
Uninitialized: Log file closed, 03/28/22 20:51:00
```

**Comment by Leon280698** [comment]
That card definitely supports OpenGL 4.5. Please set `DebugOpenGL=True` in `Save/System.ini` (Make sure to remove the leading semicolon) and post the log file

**Comment by Levan7** [comment]
@Leon280698 Well it started the game without error, yes the graphics doesn't shows graphics (pink screen) but that is a different bug I believe 
Screenshot for references in game you just get pink screen.

![Untitled](https://user-images.githubusercontent.com/5770076/160462529-91e98b44-a0ea-4858-865f-3cd5411a9747.png)

**Comment by Leon280698** [comment]
That’s not a bug, it just doesn’t support video playback yet. It works now after setting this flag? That’s a little weird…

**Comment by Levan7** [comment]
@Leon280698 gog version if it is a reference.
yes it started after setting DebugOpenGL=True in Save/System.ini
