### ISSUE TITLE
UCC Critical: Failed to find object 'Class Any.Wars'

### ISSUE THREAD

**Issue by Bxaa** [Leon280698/CT#16]
Command line: ucc batchexport X:\SW\GameData\Textures\Arena_Textures.utx texture bmp X:\Unpacked

**Comment by Leon280698** [comment]
Can't reproduce. Works fine with latest release and fresh build.
Try using the package name only without the path and see if that makes a difference for you

**Comment by Bxaa** [comment]
Yep, without path to utx it works fine
Thx

**Comment by Leon280698** [comment]
Yes, the working directory for ucc always needs to be `System`. Can be changed in code I guess but it's not worth the effort. That's just how the engine works.
As for the textures, that's a little strange. It's a problem in the Exporter so I can't change it, only write a custom one. Those textures all have the standard rgba format which should be exportable without problems. I'll look into it.

**Comment by Leon280698** [comment]
Yes, but it should still be easy to export. Most other rgba textures work fine. l6u5v5 and the other bumpmap formats can only be exported by my custom exporter. The engine itself doesn't support that.

**Comment by Leon280698** [comment]
Since this an engine bug, the solution would be to write a custom texture exporter. But for the time being just using UEViewer is an acceptable workaround.

**Comment by Bxaa** [comment]
> ther bumpmap formats can only be exported by my custom exporter

Your custom exporter support batch re import\export all textures?
I've been wanting to do a remaster for SWRC for a long time....

My projects is sw:
https://www.nexusmods.com/jediknight2/mods/7
https://www.nexusmods.com/starwarsjediknightjediacademy/mods/23

**Comment by Leon280698** [comment]
No, it’s for bumpmaps only. I don’t think there’s a batch importer
