### ISSUE TITLE
Game not using dedicated graphics card

### ISSUE THREAD

**Issue by larsschellhas** [Leon280698/CT#20]
Hey @Leon280698,
I know this is probably not of any interest for you or your fix, but maybe you have an idea how to solve this. At least I saw you commenting on Steam that your fix once solved this issue for someone:
Whenever I start RC it doesn't use my dedicated GPU, but always falls back to my integrated Intel chip.

I'm using a Surface Book 3 in maximum configuration with a GTX 1660 Ti, and an i7 10. Gen.

Naturally, the CPU/integrated GPU is actually strong enough to run the game with ease. However, the "Remastered" mod doesn't work with integrated Intel GPUs (at the moment), which is quite frustrating. 😅

So, I was wondering whether you had an idea on how to force the game to use the dGPU. I've set every possible setting in Windows settings, as well as NVIDIA Control Panel, for every executable in the directory :'D

Compatibility mode doesn't do anything either.

With other games the dGPU is used as usual, of course.

**Comment by Leon280698** [comment]
Starting the game via CT.exe should force the dedicated gpu

**Comment by larsschellhas** [comment]
Hm... It doesn't do so in my case. Task manager states it's using GPU 0, which is the integrated one. And GPU 1, the NVIDIA GPU doesn't show any sign of load.

**Comment by larsschellhas** [comment]
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/14281234/189225928-9e81b18f-705d-460e-8ad5-ad0bbc7e3710.png">

So, when I open or maximise the game, there is a short spike on the GPU 1, but then you can the GPU 0 taking the heavy load.

**Comment by Leon280698** [comment]
Idk then. Should be possible to configure that in the driver. I don't have any device with an integrated GPU so I can't test it.
Could you check if it works with the OpenGL renderer?
`CT.exe -nosaveconfig -rendev=opengl`
If it doesn't crash, chances are it is using the Nvidia gpu which can be verified by checking the log file

**Comment by larsschellhas** [comment]
Yes, that works and it is using the NVIDIA GPU, too, as already a look on the task manager showed :)

**Comment by larsschellhas** [comment]
But the Remastered mod seems to have some issues with it, too xD
![Star Wars Republic Commando 08 09 2022 23_38_22 (Groß)](https://user-images.githubusercontent.com/14281234/189230803-08ef6813-16e2-426b-89b2-bfcb1a884845.png)

Thank you anyway for your help so far! I really loved this game 15 years ago, and still do :D
