### ISSUE TITLE
Missing Window.dll file

### ISSUE THREAD

**Issue by Akexis** [Leon280698/CT#21]
[https://snipboard.io/K2vPIf.jpg](url)

I was also missing other files that gave errors - core.dll and engine.dll, but I found these and installed.
I can find window.dll as 32-bit, but not 64-bit, so it's not working on my machine. I'm wondering if it exists as a 64-bit file at all at this point, but considering the latest update was July of this year, I've got to be doing something wrong. I've tried scanning in the command prompt, tried fixing registries. I tried reinstalling Visual C++ Redistributable, but nothing has worked.

Any chance you may know a work around?

**Comment by Leon280698** [comment]
You have to put the files into the `GameData/System` directory. That’s where the dlls are.
The game is 32 bit only, there is no 64 bit version.
