### ISSUE TITLE
Missing files in ModDB release

### ISSUE THREAD

**Issue by CER10TY** [Leon280698/CT#5]
Hi,

this is only semi-related to the repo, but since I don't have a ModDB account I figured I'd leave you a note here.

I think the current version of the Graphics Fix (2.0.3) that you uploaded to ModDB is missing most of the files from 1.0, since I only get the System Folder from the zip file, but v1.0 includes folders like Animation, Properties etc. This causes other mods like RC Slightly Remastered to not work.

**Comment by Leon280698** [comment]
It's supposed to be that way. None of these are needed anymore.
